config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :nsm_assets do
    get 'user_nsm_asset', on: :collection
    get 'search_assets', on: :collection
  end
  resources :nsm_asset_types
  resources :employees do
    post 'assign_asset', on: :collection
    delete 'remove_asset', on: :collection
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'employees#index'
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :employee_assets
  has_many :nsm_assets, through: :employee_assets, as: :associated_assets
  belongs_to :department

  validates :first_name, :last_name, :joining_date, presence: true
  validates :email, :user_name, :emp_id, presence: :true, uniqueness: true

  after_initialize do |employee|
    employee.active = employee.new_record? ? true : employee.active
  end

  after_save do |employee|
    employee.employee_assets.each do |employee_asset|
      employee_asset.delete_and_unassign
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.order(:first_name).page params[:page]
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
    @associated_assets = @employee.nsm_assets
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def assign_asset
    EmployeeAsset.transaction do
      EmployeeAsset.create(employee_id: params[:employee_id], nsm_asset_id: params[:asset_id])
      nsm_asset = NsmAsset.find(params[:asset_id])
      nsm_asset.update_attribute(:assigned, true)
    end
    render text: 'success'
  end

  def remove_asset
    EmployeeAsset.transaction do
      employee = Employee.find(params[:employee_id])
      assigned_asset = employee.employee_assets.by_asset(params[:asset_id]).first
      asset = NsmAsset.find(params[:asset_id])
      assigned_asset.delete
      asset.update_attribute(:assigned, false)
    end
    render text: 'success'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email, :user_name, :joining_date, :relieving_date, :emp_id, :citrix_id, :project, :manager, :admin_access, :citrix_access, :department_id, :document_signed, :beachhead_computrace, :active)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def link_to_employee(employee, display_name = 'first_name')
    link_to employee.send(display_name), employee_path(employee), {}
  end
end

app/views/employees/_form.html.slim
= form_for(employee, :html => { :class => 'form-horizontal'}) do |f|
  - if employee.errors.any?
    #error_explanation
      h2
        = pluralize(employee.errors.count, "error")
        |  prohibited this employee from being saved:
      ul
        - employee.errors.full_messages.each do |message|
          li
            = message
  .container-fluid
    .form-group
      = f.label :first_name, class: 'control-label col-sm-2'
      .col-sm-3
        = f.text_field :first_name, class: 'form-control', placeholder: 'Enter first name'
      = f.label :last_name, class: 'control-label col-sm-2'
      .col-sm-3
        = f.text_field :last_name, class: 'form-control', placeholder: 'Enter last name'
    .form-group
      = f.label :email, class: 'control-label col-sm-2'
      .col-sm-3
        = f.text_field :email, class: 'form-control', placeholder: 'Enter email address'
      = f.label :user_name, class: 'control-label col-sm-2'
      .col-sm-3
        = f.text_field :user_name, class: 'form-control', placeholder: 'Enter Username'
    .form-group
      = f.label :joining_date, class: 'control-label col-sm-2'
      .col-sm-3
        = f.date_select :joining_date, class: 'form-control'
      = f.label :relieving_date, class: 'control-label col-sm-2'
      .col-sm-3
        = f.date_select :relieving_date, class: 'form-control', include_blank: true
    .form-group
      = f.label :emp_id, 'Employee id', class: 'control-label col-sm-2'
      .col-sm-3
        = f.text_field :emp_id, class: 'form-control', placeholder: 'Enter employee id'
      = f.label :citrix_id, 'Citrix id', class: 'control-label col-sm-2'
      .col-sm-3
        = f.text_field :citrix_id, class: 'form-control', placeholder: 'Enter citrix id'
    .form-group
      = f.label :project, class: 'control-label col-sm-2'
      .col-sm-3
        = f.text_field :project, class: 'form-control', placeholder: 'Enter project name'
      = f.label :department, class: 'control-label col-sm-2'
      .col-sm-3
        = f.collection_select :department_id, Department.all, :id, :name, {}, class: 'form-control'
    .form-group
      = f.label :manager, class: 'control-label col-sm-2'
      .col-sm-3
        = f.text_field :manager, class: 'form-control', placeholder: 'Enter manager name'
    .form-group
      = f.label :citrix_access, class: 'control-label col-sm-2'
      .col-sm-1
        = f.check_box(:citrix_access)
      = f.label :admin_access, class: 'control-label col-sm-2'
      .col-sm-1
        = f.check_box(:admin_access)
      = f.label :document_signed, class: 'control-label col-sm-2'
      .col-sm-1
        = f.check_box(:document_signed)
      = f.label :beachhead_computrace, 'Beachhead/computrace', class: 'control-label col-sm-2'
      .col-sm-1
        = f.check_box(:beachhead_computrace)
    .form-group
      = f.label :active, class: 'control-label col-sm-2'
      .col-sm-3
        = f.check_box :active, disabled: employee.new_record?
    .form-group

    .actions
      .col-sm-offset-2.col-sm-4
        = f.submit class: 'btn btn-info'
        =< link_to 'Back', employees_path, class: 'btn btn-info'

app/views/employees/edit.html.slim
h3
  | Editing Employee
= render 'form', employee: @employee
.search_assets_in_edit.container-fluid
  = hidden_field_tag('employee_id', @employee.id)
  - selected_assets = @employee.nsm_assets.map { |asset| {id: asset.id, name: asset.code} }
  = text_field_tag('search_assets', nil, {:class => 'auto_complete', 'data-url' => search_assets_nsm_assets_path, 'data-duplicate' => 'false', 'data-hint-text' => 'Type to search Unassigned Assets', 'data-no-result' => 'No Assets found', 'data-searching-text' => 'Fetching Assets', 'data-selected' => selected_assets.to_json, 'data-on-add-call-function' => 'assign_asset', 'data-on-delete-call-function' => 'un_assign_asset'})
  |  <table id="users-table" data-source="
  = user_nsm_asset_nsm_assets_path(format: :json, employee: @employee.id.to_s)
  | " class="table table-striped table-hover table-responsive table-bordered"> 
  thead
    tr
      th
        | Id
      th
        | Code
      th
        | Computer Name
      th
        | Service Tag
      th
        | Invoice Number
      th
        | Operating System
  tbody

  script
    |  autoComplete(); data_table(); 

app/views/employees/index.html.slim
.col-sm-10
  h3
    | List of Employees
.col-sm-2
  = link_to 'New Employee', new_employee_path, class: 'btn btn-info'
.container-fluid
  table.table.table-striped.table-hover.table-condensed.table-bordered
    thead
      tr
        th
          | First name
        th
          | Last name
        th
          | Email
        th
          | User name
        th
          | Joining date
        th
          | Relieving date
        th
          | Employee id
        th
    tbody
      - @employees.each do |employee|
        tr
          td
            = employee.first_name
          td
            = employee.last_name
          td
            = employee.email
          td
            = link_to_employee(employee, 'first_name')
          td
            = employee.joining_date
          td
            = employee.relieving_date
          td
            = employee.emp_id
          td
            = link_to '', edit_employee_path(employee), class: 'glyphicon glyphicon-pencil'
  = paginate @employees

app/views/employees/new.html.slim
h3
  | Add New Employee
= render 'form', employee: @employee

app/views/employees/show.html.slim
p#notice
  = notice
h3
  | Employee details
.container-fluid
  .form-group
    label.control-label.col-sm-2[for="First name"]
      | First name:
    .col-sm-10
      p.form-control-static
        = @employee.first_name
  .form-group
    label.control-label.col-sm-2[for="Last name"]
      | Last name:
    .col-sm-10
      p.form-control-static
        = @employee.last_name
  .form-group
    label.control-label.col-sm-2[for="Email"]
      | Email:
    .col-sm-10
      p.form-control-static
        = @employee.email
  .form-group
    label.control-label.col-sm-2[for="User name"]
      | User name:
    .col-sm-10
      p.form-control-static
        = @employee.user_name
  .form-group
    label.control-label.col-sm-2[for="Joining date"]
      | Joining date:
    .col-sm-10
      p.form-control-static
        = @employee.joining_date
  .form-group
    label.control-label.col-sm-2[for="Relieving date"]
      | Relieving date:
    .col-sm-10
      p.form-control-static
        = @employee.relieving_date
  .form-group
    label.control-label.col-sm-2[for="Emp"]
      | Employee id:
    .col-sm-10
      p.form-control-static
        = @employee.emp_id
  .form-group
    label.control-label.col-sm-2[for="Citrix id"]
      | citrix_id:
    .col-sm-10
      p.form-control-static
        = @employee.citrix_id
  .form-group
    label.control-label.col-sm-2[for="Project id"]
      | Project id:
    .col-sm-10
      p.form-control-static
        = @employee.project
  .form-group
    label.control-label.col-sm-2[for="manager"]
      | Manager:
    .col-sm-10
      p.form-control-static
        = @employee.manager
  .form-group
    label.control-label.col-sm-2[for="citrix access"]
      | Citrix Access:
    .col-sm-10
      p.form-control-static
        = @employee.citrix_access
  .form-group
    label.control-label.col-sm-2[for="admin access"]
      | Admin Access:
    .col-sm-10
      p.form-control-static
        = @employee.admin_access
  .form-group
    label.control-label.col-sm-2[for="department"]
      | Department:
    .col-sm-10
      p.form-control-static
        = @employee.department.name
  .form-group
    label.control-label.col-sm-2[for="document signed"]
      | Document Signed:
    .col-sm-10
      p.form-control-static
        = @employee.document_signed
  .form-group
    label.control-label.col-sm-2[for="beachhead computrace"]
      | Beachhead and Computrace:
    .col-sm-10
      p.form-control-static
        = @employee.beachhead_computrace
  = link_to 'Edit', edit_employee_path(@employee), class: 'btn btn-info'
  =< link_to 'Back', employees_path, class: 'btn btn-info'
  |  <table id="users-table" data-source="
  = user_nsm_asset_nsm_assets_path(format: :json, employee: @employee.id.to_s)
  | " class="table table-bordered"> 
  thead
    tr
      th
        | Id
      th
        | Code
      th
        | Computer Name
      th
        | Service Tag
      th
        | Invoice Number
      th
        | Operating System
  tbody

  script
    |  data_table(); 