config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :nsm_assets do
    get 'user_nsm_asset', on: :collection
    get 'search_assets', on: :collection
  end
  resources :nsm_asset_types
  resources :employees do
    post 'assign_asset', on: :collection
    delete 'remove_asset', on: :collection
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'employees#index'
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employee

  validates :name, presence: true, uniqueness: true
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :description)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.slim
= form_for(department, :html => {:class => 'form-horizontal'}) do |f|
  - if department.errors.any?
    #error_explanation
      h2
        = pluralize(department.errors.count, "error")
        |  prohibited this department from being saved:
      ul
        - department.errors.full_messages.each do |message|
          li
            = message
  .container-fluid
    .form-group
      = f.label :name, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :name, class: 'form-control', placeholder: 'Enter department name'
    .form-group
      = f.label :description, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_area :description, class: 'form-control', placeholder: 'Enter description'
    .actions
      .col-sm-offset-2.col-sm-6
        = f.submit class: 'btn btn-info'
        =< link_to 'Back', departments_path, class: 'btn btn-info'
        =< (link_to 'Show', department_path(department), class: 'btn btn-info') unless department.new_record?

app/views/departments/edit.html.slim
h3
  | Editing Department
= render 'form', department: @department

app/views/departments/index.html.slim
p#notice
  = notice
.col-sm-10
  h3
    | Departments
.col-sm-2
  = link_to 'New Department', new_department_path, class: 'btn btn-info'
.container-fluid
  table.table.table-striped.table-hover.table-condensed.table-bordered
    thead
      tr
        th
          | Name
        th
          | Description
        th
    tbody
      - @departments.each do |department|
        tr
            td
              = link_to department.name, department
            td
              = department.description
            td
              = link_to '', edit_department_path(department), class: 'glyphicon glyphicon-pencil'

app/views/departments/new.html.slim
h3
  | New Department
== render 'form', department: @department

app/views/departments/show.html.slim
p#notice
  = notice
h3
  | Department details
.container-fluid
  .form-group
    label.control-label.col-sm-2[for="Department name"]
      | Name:
    .col-sm-10
      p.form-control-static
        = @department.name
  .form-group
    label.control-label.col-sm-2[for="Description"]
      | Description:
    .col-sm-10
      p.form-control-static
        = @department.description
  =< link_to 'Edit', edit_department_path(@department), class: 'btn btn-info'
  =< link_to 'Back', departments_path, class: 'btn btn-info'