config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :nsm_assets do
    get 'user_nsm_asset', on: :collection
    get 'search_assets', on: :collection
  end
  resources :nsm_asset_types
  resources :employees do
    post 'assign_asset', on: :collection
    delete 'remove_asset', on: :collection
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'employees#index'
end

app/controllers/nsm_asset_types_controller.rb
class NsmAssetTypesController < ApplicationController
  before_action :set_nsm_asset_type, only: [:show, :edit, :update, :destroy]

  # GET /nsm_asset_types
  # GET /nsm_asset_types.json
  def index
    @nsm_asset_types = NsmAssetType.all
    respond_to :html, :xls
  end

  # GET /nsm_asset_types/1
  # GET /nsm_asset_types/1.json
  def show
  end

  # GET /nsm_asset_types/new
  def new
    @nsm_asset_type = NsmAssetType.new
  end

  # GET /nsm_asset_types/1/edit
  def edit
  end

  # POST /nsm_asset_types
  # POST /nsm_asset_types.json
  def create
    @nsm_asset_type = NsmAssetType.new(nsm_asset_type_params)

    respond_to do |format|
      if @nsm_asset_type.save
        format.html { redirect_to @nsm_asset_type, notice: 'Nsm asset type was successfully created.' }
        format.json { render :show, status: :created, location: @nsm_asset_type }
      else
        format.html { render :new }
        format.json { render json: @nsm_asset_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nsm_asset_types/1
  # PATCH/PUT /nsm_asset_types/1.json
  def update
    respond_to do |format|
      if @nsm_asset_type.update(nsm_asset_type_params)
        format.html { redirect_to @nsm_asset_type, notice: 'Nsm asset type was successfully updated.' }
        format.json { render :show, status: :ok, location: @nsm_asset_type }
      else
        format.html { render :edit }
        format.json { render json: @nsm_asset_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nsm_asset_types/1
  # DELETE /nsm_asset_types/1.json
  def destroy
    @nsm_asset_type.destroy
    respond_to do |format|
      format.html { redirect_to nsm_asset_types_url, notice: 'Nsm asset type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nsm_asset_type
      @nsm_asset_type = NsmAssetType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nsm_asset_type_params
      params.require(:nsm_asset_type).permit(:name, :description, :charger, :laptop_bag)
    end
end

app/helpers/nsm_asset_types_helper.rb
module NsmAssetTypesHelper
end

app/views/nsm_asset_types/_form.html.slim
= form_for(nsm_asset_type, :html => {:class => 'form-horizontal'}) do |f|
  - if nsm_asset_type.errors.any?
    #error_explanation
      h2
        = pluralize(nsm_asset_type.errors.count, "error")
        |  prohibited this nsm_asset_type from being saved:
      ul
        - nsm_asset_type.errors.full_messages.each do |message|
          li
            = message
  .container-fluid
    .form-group
      = f.label :name, class: 'control-label col-sm-2'
      .col-sm-3
        = f.text_field :name, class: 'form-control', placeholder: 'Enter asset name'
    .form-group
      = f.label :description, class: 'control-label col-sm-2'
      .col-sm-3
        = f.text_area :description, class: 'form-control', placeholder: 'Enter description'
    .form-group
      = f.label :charger, class: 'control-label col-sm-2'
      .col-sm-1
        = f.check_box(:charger)
      = f.label :laptop_bag, class: 'control-label col-sm-2'
      .col-sm-1
        = f.check_box(:laptop_bag)
    .actions
      .col-sm-offset-2.col-sm-4
        = f.submit class: 'btn btn-info'
        =< link_to 'Back', nsm_asset_types_path, class: 'btn btn-info'

app/views/nsm_asset_types/edit.html.slim
h3
  | Editing Nsm Asset Type
= render 'form', nsm_asset_type: @nsm_asset_type

app/views/nsm_asset_types/index.html.slim
.col-sm-9
  h3
    | Nsm Asset Types
.col-sm-3
  = link_to 'New Asset Type', new_nsm_asset_type_path, class: 'btn btn-info'
  =< link_to 'Export', nsm_asset_types_path(format: 'xls'), class: 'btn btn-success'
.container-fluid
  table.table.table-striped.table-hover.table-condensed.table-bordered
    thead
      tr
        th
          | Name
        th
          | Description
        th
          | #Purchased
        th
          | #Assigned
        th
          | #Available
        th
    tbody
      - @nsm_asset_types.each do |nsm_asset_type|
        tr
          td
            = link_to nsm_asset_type.name, nsm_asset_type
          td
            = nsm_asset_type.description
          td
            = nsm_asset_type.purchased_count
          td
            = nsm_asset_type.assigned_count
          td
            = nsm_asset_type.available_count
          td
            = link_to '', edit_nsm_asset_type_path(nsm_asset_type), class: 'glyphicon glyphicon-pencil'

app/views/nsm_asset_types/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Assets_list">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
        <Cell><Data ss:Type="String">#Purchased</Data></Cell>
        <Cell><Data ss:Type="String">#Assigned</Data></Cell>
        <Cell><Data ss:Type="String">#Available</Data></Cell>
      </Row>
      <% @nsm_asset_types.each do |asset_type| %>
          <Row>
            <Cell><Data ss:Type="String"><%= asset_type.name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= asset_type.description %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= asset_type.purchased_count %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= asset_type.assigned_count %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= asset_type.available_count %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/nsm_asset_types/new.html.slim
h3
  | New Nsm Asset Type
= render 'form', nsm_asset_type: @nsm_asset_type

app/views/nsm_asset_types/show.html.slim
p#notice
  = notice
.container-fluid
  h3
    | NSM Asset details
  .form-group
    label.control-label.col-sm-2[for="Name"]
      | Name:
    .col-sm-10
      p.form-control-static
        = @nsm_asset_type.name
  .form-group
    label.control-label.col-sm-2[for="Description"]
      | Description:
    .col-sm-10
      p.form-control-static
        = @nsm_asset_type.description
  .form-group
    label.control-label.col-sm-2[for="Charger"]
      | Charger:
    .col-sm-10
      p.form-control-static
        = @nsm_asset_type.charger
  .form-group
    label.control-label.col-sm-2[for="Charger"]
      | Laptop Bag:
    .col-sm-10
      p.form-control-static
        = @nsm_asset_type.laptop_bag
  =< link_to 'Edit', edit_nsm_asset_type_path(@nsm_asset_type), class: 'btn btn-info'
  =< link_to 'Back', nsm_asset_types_path, class: 'btn btn-info'