config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :nsm_assets do
    get 'user_nsm_asset', on: :collection
    get 'search_assets', on: :collection
  end
  resources :nsm_asset_types
  resources :employees do
    post 'assign_asset', on: :collection
    delete 'remove_asset', on: :collection
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'employees#index'
end

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'AMAFA  ', employees_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">

      <%= content_tag(:li, { class: params[:controller].eql?('employees') ? 'active' : '' }) { link_to 'Employees', employees_path } %>
      <%= content_tag(:li, { class: params[:controller].eql?('nsm_assets') ? 'active' : '' }) { link_to 'Assets', nsm_assets_path } %>
      <%= content_tag(:li, { class: params[:controller].eql?('nsm_asset_types') ? 'active' : '' }) { link_to 'Asset Types', nsm_asset_types_path } %>
      <%= content_tag(:li, { class: params[:controller].eql?('departments') ? 'active' : '' }) { link_to 'Departments', departments_path } %>
      <%= (content_tag(:li, { class: params[:controller].eql?('users/registrations') ? 'active' : '' }) { link_to 'Add User', new_user_registration_path }) if current_user.try(:admin?) %>

    </ul>
    <ul class="nav navbar-nav navbar-right">
      <%= content_tag(:li) { link_to 'Sign out', destroy_user_session_path, method: :delete } %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amafa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render partial: 'layouts/nav_bar' if user_signed_in? %>
    <%= yield %>
  </body>
</html>